#!/usr/bin/env bash

# ============================================================================================= #
#: Title           : update                                                                     #
#: Sypnosis        : update                                                                     #
#: Date Created    : Thu May  8 02:42:32 PHT 2014 / Wed May  7 18:42:32 UTC 2014                #
#: Last Edit       : Wed Mar 18 15:29:41 PHT 2015 / Wed Mar 18 07:29:41 UTC 2015                #
#: License         : GPLv3                                                                      #
#: Version         : 1.4.1                                                                      #
#: Author          : Jason V. Ferrer '<jetchisel@opensuse.org>'                                 #
#: Description     : Disable multiversion,deltarpm,autorefresh. Enable package cache and update.#
#: Options         : None                                                                       #
#: Home Page       : None                                                                       #
#: ExtComm         : ed,cp,curl,grep,pgrep,su,zypper                                            #
# ============================================================================================= #

# ********************************************************************************************* #
#                                                                                               #
#   Warn and die functions, for exit messages and default status or an optional exit status.    #
#                                                                                               #
# ********************************************************************************************* #

warn() {
  printf '%s\n' "${BASH_SOURCE##*/}: $*" >&2
}

die() {
  local st=$?
  case $2 in
    *[^0-9]*|'') :;;
    *) st=$2;;
  esac
  warn "$1"
  exit "$st"
}

# ********************************************************************************************* #
#                                                                                               #
#  If not root exit. (Aritmethic context in bash, 0 has an exit status of 1 which means error.) #
#                                                                                               #
# ********************************************************************************************* #

(( EUID )) && die "Root privileges are required for updating system packages."

# ********************************************************************************************* #
#                                                                                               #
#           Check if the required apps/executables is in your PATH, exit otherwise.             #
#                                                                                               #
# ********************************************************************************************* #

Missing=()
ExtComm=(ed cp curl grep pgrep su zypper)
ExitMessage="Please install the following: "
MissingMessage="is either not installed or it is not in your PATH!"

for apps in "${ExtComm[@]}"; do
  if ! type -P "$apps" >/dev/null; then
    printf '%s %s\n' "$apps" "$MissingMessage" >&2
    Missing+=("$apps")
  fi
done

(( ${#Missing[@]} )) && die "$ExitMessage[${Missing[*]}] exiting now!" 127

# ********************************************************************************************* #
#                                                                                               #
#   If you despise apper and packageki (for being stubborn) Uncomment this if-statement. :).    #
#                                                                                               #
# ********************************************************************************************* #

#if [[ $DISPLAY ]]; then
#  apper_pid=$(pgrep -x apper) && kill -9 "$apper_pid"
#  packagekit_pid=$(pgrep -x packagekitd) && kill -9 "$packagekit_pid"
#fi

# ********************************************************************************************* #
#                                                                                               #
#     Assign zypp.conf in the variable zypp but exit with an error if it does not exists.       #
#                                                                                               #
# ********************************************************************************************* #

zypp=/etc/zypp/zypp.conf

[[ -s $zypp ]] || die "$zypp no such file or directory!"

# ********************************************************************************************* #
#                                                                                               #
#      Create a backup of zypp.conf with an extension .default if it is not already created.    #
#                                                                                               #
# ********************************************************************************************* #

if [[ ! -s ${zypp}.default ]]; then
  cp "$zypp" "${zypp}.default" || die "Check your permissions!"
fi

# ********************************************************************************************* #
#                                                                                               #
#  Comment out lines starting from "multiversion =" and "multiversion." in /etc/zypp/zypp.conf  #
#                                                                                               #
# ********************************************************************************************* #

if grep -q "^multiversion[[:space:].]" "$zypp"; then
  ed -s "$zypp" <<< $'g/^multiversion[[:space:].]/s/^/# /\nw\nq'
fi

# ********************************************************************************************* #
#                                                                                               #
#                   Uncomment both delta rpm entries in /etc/zypp/zypp.conf                     #
#                                                                                               #
# ********************************************************************************************* #

if grep -q "^#[[:space:]]*download.use_deltarpm" "$zypp"; then
  ed -s "$zypp" <<< $'g/^#[[:space:]]*download.use_deltarpm/s/^#[[:space:]]*//\nw\nq'
fi

# ********************************************************************************************* #
#                                                                                               #
#          Replace the value of download.use_deltarpm with false if it is true value.           #
#                                                                                               #
# ********************************************************************************************* #

if grep -q "^download.use_deltarpm.*[[:space:]]*=*[[:space:]]*true$" "$zypp"; then
  ed -s "$zypp" <<< $'g/^\(download\.use_deltarpm.*[[:space:]]*=\).*$/s//\\1 false/\nw\nq'
fi

# ********************************************************************************************* #
#                                                                                               #
#   Create an array of all the repos in repos.d, exit if there is none ( just making sure :) )  #
#                                                                                               #
# ********************************************************************************************* #

shopt -s nullglob

AllRepos=(/etc/zypp/repos.d/*.repo) || die "You don't seem to have any reopsitory!"

# ********************************************************************************************* #
#                                                                                               #
#   Create an array of FileName and PathName from all the enabled repos by skipping enabled=0   #
#                                                                                               #
# ********************************************************************************************* #

PathNameEnabledRepos=()
FileNameEnabledRepos=()

for repos in "${AllRepos[@]}"; do
  grep -Fq 'enabled=0' "$repos" && continue
  PathNameEnabledRepos+=("$repos")
  repos=${repos##*/}
  FileNameEnabledRepos+=("${repos%.*}")
done

# ********************************************************************************************* #
#                                                                                               #
#          Disable autorefresh of repos (if any) regardless if it is enabled or not.            #
#                                                                                               #
# ********************************************************************************************* #

for repos in "${AllRepos[@]}"; do
  grep -Fq 'autorefresh=1' "$repos" && ed -s "$repos" <<< $'/\(autorefresh=\).*/s//\\10/\nw\nq'
done

# ********************************************************************************************* #
#                                                                                               #
#    keep packages on all enabled repos, either append keeppackages=1 or replace 0 with 1.      #
#                                                                                               #
# ********************************************************************************************* #

for repos in "${PathNameEnabledRepos[@]}"; do
  if ! grep -q keeppackages "$repos"; then
    ed -s "$repos" <<< $'$a\nkeeppackages=1\n.\nw\nq'
  elif grep -Fq 'keeppackages=0' "$repos"; then
    ed -s "$repos" <<< $'/\(keeppackages=\).*/s//\\11/\nw\nq'
  fi
done

# ********************************************************************************************* #
#                                                                                               #
#           Check if internet connection is up, otherwise exit with an error message.           #
#                                                                                               #
# ********************************************************************************************* #

if ! curl -Lsf google.com >/dev/null; then
  die 'You are not online, please check your network settings!'
fi

# ********************************************************************************************* #
#                                                                                               #
#       if download.opensuse.org is not responding to you then exit with an error message.      #
#                                                                                               #
# ********************************************************************************************* #

curl -Lsf download.opensuse.org >/dev/null || die 'Could connect to download.opensuse.org!'

# ********************************************************************************************* #
#                                                                                               #
#                            Refresh all enabled repos and update.                              #
#                                                                                               #
# ********************************************************************************************* #

zypper ref "${FileNameEnabledRepos[@]}" && zypper up

# ********************************************************************************************* #
#                                                                                               #
#                                     Set the exit staus.                                       #
#                                                                                               #
# ********************************************************************************************* #

exit 0

# ============================================================================================= #
#                                                                                               #
#                                    >>> END OF SCRIPT <<<                                      #
#                                                                                               #
# ============================================================================================= #
